# Generated by Django 4.2.3 on 2023-08-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHomeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
