# Generated by Django 4.2.3 on 2023-08-04 09:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_alter_viewhomemodels_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhomemodels',
            name='createdDate',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
