# Generated by Django 4.2.3 on 2023-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0005_alter_viewhomemodels_createddate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhomemodels',
            options={'verbose_name': 'تعداد بازدید', 'verbose_name_plural': 'تعداد بازدید ها'},
        ),
        migrations.AlterField(
            model_name='viewhomemodels',
            name='createdDate',
            field=models.DateTimeField(),
        ),
    ]
