# Generated by Django 4.2.3 on 2023-12-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0007_alter_viewhomemodels_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarinpallClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='لینک درگاه پرداخت')),
            ],
            options={
                'verbose_name': 'لینک درگاه پرداخت زرین پال',
                'verbose_name_plural': 'لینک درگاه پرداخت زرین پال',
            },
        ),
    ]
