# Generated by Django 4.2.3 on 2023-12-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0008_zarinpallclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام را وارد کنید')),
            ],
            options={
                'verbose_name': 'ارسال پیام',
                'verbose_name_plural': 'ارسال پیام',
            },
        ),
    ]
