# Generated by Django 4.2.3 on 2023-09-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharsooModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='charsoo/image', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'سامانه چارسو',
                'verbose_name_plural': 'سامانه چارسو',
            },
        ),
    ]
