# Generated by Django 4.2.3 on 2023-08-09 09:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان رویداد')),
                ('short', models.TextField(verbose_name='خلاصه توضیحات رویداد')),
                ('body', ckeditor.fields.RichTextField(verbose_name='توضیحات کلی رویداد')),
                ('price_event', models.IntegerField(default=0, verbose_name='هزینه رویداد(صفر به معنی رایگان بودن رویداد است)')),
                ('how_to_hold', models.CharField(choices=[('حضوری', 'حضوری'), ('آنلاین', 'آنلاین')], default='حضوری', max_length=50, verbose_name='نحوه برگذاری')),
                ('capacity', models.IntegerField(default=0, verbose_name='ظرفیت رودیداد(صفر به یعنی بدون محدودیت ظرفیت)')),
                ('the_date_of_the_event', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ برگذاری رویداد')),
                ('start_register', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع ثبت نام در رویداد')),
                ('end_of_register', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان ثبت نام در رویداد')),
                ('users', models.ManyToManyField(related_name='event_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربران رودیداد')),
            ],
        ),
    ]
