# Generated by Django 4.2.3 on 2023-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmodel',
            name='image',
            field=models.FileField(default=1, upload_to='images/events/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='user_of_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد کاربران ثبت نام شده'),
        ),
    ]
