# Generated by Django 4.2.3 on 2023-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0002_eventsmodel_image_eventsmodel_user_of_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmodel',
            name='user_of_count',
        ),
    ]
