# Generated by Django 4.2.3 on 2023-08-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0004_alter_eventsmodel_options_alter_eventsmodel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmodel',
            name='categoryevent',
            field=models.CharField(choices=[('رویداد', 'رویداد'), ('همایش', 'همایش'), ('سمینار', 'سمینار'), ('جشنواره', 'جشنواره'), ('دوره آموزش', 'دوره آموزشی')], default=1, max_length=100, verbose_name='دسته بندی رویداد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='image',
            field=models.FileField(upload_to='images/events/', verbose_name='تصویر'),
        ),
    ]
