# Generated by Django 4.2.3 on 2023-08-10 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventsApp', '0005_eventsmodel_categoryevent_alter_eventsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربران رویداد'),
        ),
    ]
