# Generated by Django 4.2.3 on 2023-08-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0006_alter_eventsmodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='the_date_of_the_event',
            field=models.DateTimeField(verbose_name='تاریخ برگذاری رویداد'),
        ),
    ]
