# Generated by Django 4.2.3 on 2023-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0007_alter_eventsmodel_the_date_of_the_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='end_of_register',
            field=models.DateTimeField(verbose_name='تاریخ پایان ثبت نام در رویداد'),
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='start_register',
            field=models.DateTimeField(verbose_name='تاریخ شروع ثبت نام در رویداد'),
        ),
    ]
