# Generated by Django 4.2.3 on 2023-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0008_alter_eventsmodel_end_of_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmodel',
            name='location',
            field=models.CharField(default=1, max_length=50, verbose_name='مکان رویداد'),
            preserve_default=False,
        ),
    ]
