# Generated by Django 4.2.3 on 2023-07-22 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GuildRoomApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildroommodel',
            options={'verbose_name': 'اتاق اصناف', 'verbose_name_plural': 'اتاق اصناف'},
        ),
        migrations.RemoveField(
            model_name='guildroommodel',
            name='post',
        ),
        migrations.AlterField(
            model_name='guildroommodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام اتحادیه'),
        ),
        migrations.AlterField(
            model_name='guildroommodel',
            name='user',
            field=models.ManyToManyField(limit_choices_to={'guild_member': True}, to=settings.AUTH_USER_MODEL, verbose_name='افراد'),
        ),
    ]
