# Generated by Django 4.2.3 on 2023-07-23 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GuildRoomApp', '0002_alter_guildroommodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildroommodel',
            name='user',
            field=models.ManyToManyField(limit_choices_to={'guild_member': True}, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='افراد'),
        ),
    ]
