# Generated by Django 4.2.3 on 2023-07-24 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GuildRoomApp', '0004_guildroommodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کمیسون')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('user', models.ManyToManyField(limit_choices_to={'commissions_member': True}, related_name='Comision', to=settings.AUTH_USER_MODEL, verbose_name='افراد')),
            ],
            options={
                'verbose_name': 'کمیسیون',
                'verbose_name_plural': 'کمیسیون ها',
            },
        ),
    ]
