# Generated by Django 4.2.3 on 2023-09-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuildRoomApp', '0005_commissionsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildroommodel',
            options={'verbose_name': 'اتحادیه', 'verbose_name_plural': 'اتحادیه ها'},
        ),
    ]
