# Generated by Django 4.2.3 on 2023-08-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactByMeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPrecious',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=100, verbose_name='شماره تلفن')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('is_publish', models.BooleanField(default=False, verbose_name='منتشر شود؟')),
            ],
            options={
                'verbose_name': 'شی گمشده',
                'verbose_name_plural': 'اشیا گمشده',
            },
        ),
    ]
