# Generated by Django 4.2.3 on 2023-08-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactByMeapp', '0003_work_force'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_force',
            name='number_register',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره ثبت اتحادیه'),
        ),
    ]
