# Generated by Django 4.2.3 on 2023-12-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactByMeapp', '0004_work_force_number_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostprecious',
            name='image',
            field=models.FileField(default=1, upload_to='lost/images'),
            preserve_default=False,
        ),
    ]
