# Generated by Django 4.2.3 on 2023-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guild_member',
            field=models.BooleanField(default=False),
        ),
    ]
