# Generated by Django 4.2.3 on 2023-07-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0002_user_guild_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='آدرس ایمیل'),
        ),
    ]
