# Generated by Django 4.2.3 on 2023-07-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('رئیس', 'رئیس'), ('نائب رئیس اول', 'نائب رئیس اول'), ('نائب رئیس دوم', 'نائب رئیس دوم'), ('مدیراجرایی', 'مدیر اجرایی'), ('خزانه دار', 'خزانه دار'), ('کاربر عادی', 'کاربر عادی')], default='کاربر عادی', max_length=50, null=True, verbose_name='سمت'),
        ),
    ]
