# Generated by Django 4.2.3 on 2023-07-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0006_user_fullname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='guild_member',
            field=models.BooleanField(default=False, verbose_name='عضو هیئت رئیسه اصناف است؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='users/images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='کاربر فعال است؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین وبسایت(به همه چیز دسترسی دارد!!)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_publishing_news',
            field=models.BooleanField(default=False, verbose_name='اجازه ارسال اخبار دارد؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('رئیس', 'رئیس'), ('نائب رئیس اول', 'نائب رئیس اول'), ('نائب رئیس دوم', 'نائب رئیس دوم'), ('مدیراجرایی', 'مدیر اجرایی'), ('خزانه دار', 'خزانه دار'), ('کاربر عادی', 'کاربر عادی')], default='کاربر عادی', max_length=50, null=True, verbose_name='سمت-مقام'),
        ),
    ]
