# Generated by Django 4.2.3 on 2023-07-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0007_alter_user_options_alter_user_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commissions_member',
            field=models.BooleanField(default=False, verbose_name='عضو کمیسیون می باشد؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('رئیس', 'رئیس'), ('نائب رئیس اول', 'نائب رئیس اول'), ('نائب رئیس دوم', 'نائب رئیس دوم'), ('مدیراجرایی', 'مدیر اجرایی'), ('خزانه دار', 'خزانه دار'), ('کاربر عادی', 'کاربر عادی'), ('عضو', 'عضو')], default='کاربر عادی', max_length=50, null=True, verbose_name='سمت-مقام'),
        ),
    ]
