# Generated by Django 4.2.3 on 2023-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0008_user_commissions_member_alter_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='board_of_directors',
            field=models.BooleanField(default=False, verbose_name='عضو هیئت رئیسه می باشد؟'),
        ),
    ]
