# Generated by Django 4.2.3 on 2023-08-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0009_user_board_of_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guild_member',
            field=models.BooleanField(default=False, verbose_name='عضو اتاق اصناف است؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین وبسایت(به همه چیز دسترسی دارد)'),
        ),
    ]
