# Generated by Django 4.2.3 on 2023-08-04 18:54

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0010_alter_user_guild_member_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
