# Generated by Django 4.2.3 on 2023-08-07 17:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0011_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
    ]
