# Generated by Django 4.2.3 on 2023-08-09 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0012_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('code', models.CharField(max_length=15)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 14, 4, 24, 50110, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
