# Generated by Django 4.2.3 on 2023-08-09 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0013_otpclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpclass',
            name='fullname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpclass',
            name='password',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpclass',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 14, 31, 36, 10089, tzinfo=datetime.timezone.utc)),
        ),
    ]
