# Generated by Django 4.2.3 on 2023-08-09 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0014_otpclass_fullname_otpclass_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpclass',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 32, 55, 826873, tzinfo=datetime.timezone.utc)),
        ),
    ]
