# Generated by Django 4.2.3 on 2023-08-09 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0015_alter_otpclass_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpclass',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 33, 23, 802218, tzinfo=datetime.timezone.utc)),
        ),
    ]
