# Generated by Django 4.2.3 on 2023-08-09 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcountApp', '0016_alter_otpclass_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetTokenOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=50)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 32, 34, 828695, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='otpclass',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 32, 34, 828695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otpclass',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otpclass',
            name='password',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
