# Generated by Django 4.2.3 on 2023-07-22 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GuildRoomApp', '0002_alter_guildroommodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('writer_guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuildRoomApp.guildroommodel')),
            ],
        ),
    ]
