# Generated by Django 4.2.3 on 2023-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodels',
            name='image',
            field=models.FileField(default=1, upload_to='image/news'),
            preserve_default=False,
        ),
    ]
