# Generated by Django 4.2.3 on 2023-07-22 18:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_newsmodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
