# Generated by Django 4.2.3 on 2023-07-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_newsmodels_pub_date_newsmodels_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodels',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
