# Generated by Django 4.2.3 on 2023-07-24 08:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0007_alter_newsmodels_options_alter_newsmodels_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.FileField(upload_to='imageGallery/image', verbose_name='کاور تصویری')),
                ('video', models.FileField(blank=True, null=True, upload_to='imageGallery/video', verbose_name='ویدئو')),
                ('title', models.CharField(max_length=150, verbose_name='مقدمه')),
                ('body', ckeditor.fields.RichTextField(verbose_name='متن خبر')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'گالری تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
