# Generated by Django 4.2.3 on 2023-07-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0008_imagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='اسلاگ:این قسمت پر نشود!'),
        ),
    ]
