# Generated by Django 4.2.3 on 2023-07-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0009_imagegallery_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='cover',
            new_name='image',
        ),
    ]
