# Generated by Django 4.2.3 on 2023-07-24 13:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0011_alter_newsmodels_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='pub_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
