# Generated by Django 4.2.3 on 2023-07-24 13:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0012_alter_newsmodels_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
