# Generated by Django 4.2.3 on 2023-08-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuildRoomApp', '0005_commissionsmodel'),
        ('NewsApp', '0013_alter_imagegallery_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='writer_guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuildRoomApp.guildroommodel', verbose_name='اتحادیه مربوطه'),
        ),
    ]
