# Generated by Django 4.2.3 on 2023-09-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0017_alter_imagegallery_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodels',
            options={'ordering': ('-pub_date',), 'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
    ]
