# Generated by Django 4.2.3 on 2023-09-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisionApp', '0002_alter_supervision_user'),
        ('NewsApp', '0018_alter_newsmodels_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodels',
            name='supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervisionApp.supervision', verbose_name='نظارت و بازبایی مربوطه'),
        ),
    ]
