# Generated by Django 4.2.3 on 2023-08-14 08:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RulesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('category', models.CharField(choices=[('دستورالعمل های اجرایی', 'دستورالعمل های اجرایی'), ('آئین نامه اجرایی', 'آئین نامه اجرایی'), ('قانون نظام صنفی', 'قانون نظام صنفی')], max_length=30, verbose_name='دسته بندی')),
                ('file', models.FileField(upload_to='rules/File', verbose_name='فایلpdf')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن قانون')),
            ],
            options={
                'verbose_name': 'قانون',
                'verbose_name_plural': 'قوانین',
            },
        ),
    ]
