# Generated by Django 4.2.3 on 2023-08-09 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventsApp', '0004_alter_eventsmodel_options_alter_eventsmodel_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('is_pay', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('pay_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پرداخت')),
                ('event', models.ManyToManyField(related_name='ordershop', to='EventsApp.eventsmodel', verbose_name='رویداد مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderShop', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
