# Generated by Django 4.2.3 on 2023-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentsApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordershop',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
    ]
