# Generated by Django 4.2.3 on 2023-08-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentsApps', '0002_alter_ordershop_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershop',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordershop',
            name='event',
        ),
    ]
