# Generated by Django 4.2.3 on 2023-08-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0008_alter_eventsmodel_end_of_register_and_more'),
        ('PaymentsApps', '0003_rename_price_ordershop_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='EventsApp.eventsmodel', verbose_name='رویداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='PaymentsApps.ordershop', verbose_name='سبد خرید')),
            ],
        ),
    ]
