# Generated by Django 4.2.3 on 2023-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0008_alter_eventsmodel_end_of_register_and_more'),
        ('PaymentsApps', '0006_alter_ordershop_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershop',
            name='event',
            field=models.ManyToManyField(related_name='orderItem', to='EventsApp.eventsmodel', verbose_name='رویداد'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
