# Generated by Django 4.2.3 on 2023-09-30 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نظارت و بازرسی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('user', models.ManyToManyField(limit_choices_to={'commissions_member': True}, related_name='Supervision', to=settings.AUTH_USER_MODEL, verbose_name='افراد')),
            ],
            options={
                'verbose_name': 'نظارت و بازرسی',
                'verbose_name_plural': 'نظارت و بازرسی',
            },
        ),
    ]
