# Generated by Django 4.2.3 on 2023-09-30 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervisionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervision',
            name='user',
            field=models.ManyToManyField(limit_choices_to={'is_supervision': True}, related_name='Supervision', to=settings.AUTH_USER_MODEL, verbose_name='افراد'),
        ),
    ]
